# =====================
# SITE BASICS
# =====================
title: "Altolane Jackson III — Backend Web Developer"
description: "Portfolio showcasing secure backend systems, automation, and case studies."
url: "https://ajjack0303.github.io" # GitHub Pages root
baseurl: "/AJ-DAE" # Repository name (case-sensitive)

# =====================
# THEME (Minimal Mistakes)
# =====================
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default"

# =====================
# AUTHOR PROFILE
# =====================
author:
  name: "Altolane Jackson III"
  avatar: "/assets/img/profile.jpg"
  bio: "Backend development student combining secure, scalable systems with creative technology projects."
  email: "aj.jackson0303@gmail.com"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/ajjack0303"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/altolane-jackson-39a6a9170"

# =====================
# NAVIGATION (top menu)
# =====================
# Navigation is configured in _data/navigation.yml for Minimal Mistakes theme

# =====================
# BRANDING
# =====================
logo: "/assets/img/dae-logo.avif"

# =====================
# PLUGINS (safe + GitHub Pages supported)
# =====================
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache
  - jekyll-remote-theme

# =====================
# BUILD & MARKDOWN
# =====================
markdown: kramdown
highlighter: rouge
permalink: pretty

# =====================
# GLOBAL DEFAULTS (layout, ToC, author)
# =====================
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      toc: true
      toc_sticky: true
      author_profile: true

# =====================
# EXCLUDES (optional)
# =====================
# exclude:
#   - README.md
#   - Gemfile
#   - Gemfile.lock
#   - .sass-cache/
#   - .jekyll-cache/
#   - node_modules/
#   - vendor/
