source "https://rubygems.org"

gem "jekyll", "~> 4.3"
gem "jekyll-remote-theme"
gem "jekyll-sass-converter", "~> 2.2"



gem "jekyll-feed", "~> 0.17.0"

gem "jekyll-seo-tag", "~> 2.8"

gem "jekyll-include-cache", "~> 0.2.1"
